name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: avsm/setup-ocaml@master
    - name: Initialize opam
      run: opam pin add -n .
    - name: Install dependencies and build
      run: opam depext -yti rtmp
    - name: Install additional programs
      run: sudo apt-get install -y ffmpeg
    - name: Run tests
      run: |
        eval $(opam config env)
        dune runtest
        cd examples
        make run
